name: sarcgraph-dev
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - ffmpeg=4.2.2
  - matplotlib=3.5.2
  - numpy=1.23.5
  - networkx
  - pandas
  - pytest
  - pytest-cov
  - scikit-image
  - scikit-learn
  - scipy
  - sk-video
  - trackpy
  - black
  - flake8
  - sphinx
  - sphinx_rtd_theme
  - sphinx-design
  - sphinx-copybutton
  - nbsphinx
  - ipykernel
  - pandoc
